name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [netstandard2.0, netstandard2.1, net6.0, net7.0]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      
      - name: Restore test dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release -f ${{ matrix.target }} --no-restore