name: Release Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: Build library for .NET Standard 2.0
      run: dotnet build -c Release -f netstandard2.0
    - name: Build library for .NET Standard 2.1
      run: dotnet build -c Release -f netstandard2.1
    - name: Build library for .NET 6.0
      run: dotnet build -c Release -f net6.0
    - name: Build library for .NET 7.0
      run: dotnet build -c Release -f net7.0

    - name: Build NuGet Package
      run: dotnet pack -c Release -p:PackageVersion=${{  github.ref_name }} --output dist


    - name: Upload nuget package artifact
      uses: actions/upload-artifact@v3
      with:
        name: Nuget package
        path: dist/*.nupkg

    - name: Publish NuGet Package
      run: dotnet nuget push "dist/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
